### ISSUE TITLE
Unable to download alexnet.py and Word2VecVec

### ISSUE THREAD

**Issue by sree5472** [gimpong/AAAI21-WSDHQ#1]
The pre-trained files of AlexNet (alexnet.npy) and Word2Vec (GoogleNews-vectors-negative300.bin.gz) can be downloaded from Baidu Wangpan (Web Drive, password: ocmv).

**Comment by gimpong** [comment]
Yes, did you encounter any problems?

**Comment by gimpong** [comment]
Hi, 

I just rechecked the file and ,everything seems normal. Maybe you could check if you'd be able to connect to Baidu Net Disk?
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/20691663-e88d-4b46-b9a8-eea4abab7476" />

Best

**Comment by sree5472** [comment]
can you please specify the steps how to connect Baidu Net Disk? 
unable to connect Baidu network Disk.
![image](https://github.com/user-attachments/assets/755e6f91-b04e-4216-a17f-873dcc1a9ac9)

**Comment by gimpong** [comment]
You can click and open the link in the README on your computer, and the files are available without needing to log in.
<img width="450" alt="image" src="https://github.com/user-attachments/assets/87db47bb-ebdb-45e4-aac5-69c4a7a36cc9" />

I just tried it and it seems that Baidu Cloud now requires logging in to download files. You may register an account before downloading. The files are accessible. Sorry for any inconvenience.

**Comment by sree5472** [comment]
while registering it will not allowed other country people .so is there any other way to get The pre-trained files of AlexNet (alexnet.npy) and Word2Vec (GoogleNews-vectors-negative300.bin.gz) it will be helpfull for me.
<img width="384" alt="image" src="https://github.com/user-attachments/assets/1c155fe5-62d4-45cc-aa37-abc603ead718" />

**Comment by gimpong** [comment]
@sree5472 
Hi, 

I have just found another source for these two files:
- [`alexnet.npy`](https://github.com/thulab/DeepHash/releases/download/v0.1/reference_pretrain.npy.zip)
- [`GoogleNews-vectors-negative300.bin.gz`](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing)

Cheers,
Jinpeng
